Repository smalot/pdfparser, pull requests merged in 2020-05, with the labels that each got.

#290 Define lowest deps
  .travis.yml
  composer.json
Labels: enhancement, unit tests

#292 Add FriendsOfPHP/PHP-CS-Fixer to "require-dev" to enforce coding styles
  .gitignore
  .php_cs
  composer.json
  src/Smalot/PdfParser/Document.php
  src/Smalot/PdfParser/Element.php
  src/Smalot/PdfParser/Element/ElementArray.php
  src/Smalot/PdfParser/Element/ElementBoolean.php
  src/Smalot/PdfParser/Element/ElementDate.php
  src/Smalot/PdfParser/Element/ElementHexa.php
  src/Smalot/PdfParser/Element/ElementMissing.php
  src/Smalot/PdfParser/Element/ElementName.php
  src/Smalot/PdfParser/Element/ElementNull.php
  src/Smalot/PdfParser/Element/ElementNumeric.php
  src/Smalot/PdfParser/Element/ElementString.php
  src/Smalot/PdfParser/Element/ElementStruct.php
  src/Smalot/PdfParser/Element/ElementXRef.php
  src/Smalot/PdfParser/Encoding.php
  src/Smalot/PdfParser/Encoding/ISOLatin1Encoding.php
  src/Smalot/PdfParser/Encoding/ISOLatin9Encoding.php
  src/Smalot/PdfParser/Encoding/MacRomanEncoding.php
  src/Smalot/PdfParser/Encoding/StandardEncoding.php
  src/Smalot/PdfParser/Encoding/WinAnsiEncoding.php
  src/Smalot/PdfParser/Font.php
  src/Smalot/PdfParser/Font/FontCIDFontType0.php
  src/Smalot/PdfParser/Font/FontCIDFontType2.php
  src/Smalot/PdfParser/Font/FontTrueType.php
  src/Smalot/PdfParser/Font/FontType0.php
  src/Smalot/PdfParser/Font/FontType1.php
  src/Smalot/PdfParser/Font/FontType3.php
  src/Smalot/PdfParser/Header.php
  src/Smalot/PdfParser/PDFObject.php
  src/Smalot/PdfParser/Page.php
  src/Smalot/PdfParser/Pages.php
  src/Smalot/PdfParser/Parser.php
  src/Smalot/PdfParser/Tests/Units/Document.php
  src/Smalot/PdfParser/Tests/Units/Element.php
  src/Smalot/PdfParser/Tests/Units/Element/ElementArray.php
  src/Smalot/PdfParser/Tests/Units/Element/ElementBoolean.php
  src/Smalot/PdfParser/Tests/Units/Element/ElementDate.php
  src/Smalot/PdfParser/Tests/Units/Element/ElementHexa.php
  src/Smalot/PdfParser/Tests/Units/Element/ElementMissing.php
  src/Smalot/PdfParser/Tests/Units/Element/ElementName.php
  src/Smalot/PdfParser/Tests/Units/Element/ElementNull.php
  src/Smalot/PdfParser/Tests/Units/Element/ElementNumeric.php
  src/Smalot/PdfParser/Tests/Units/Element/ElementString.php
  src/Smalot/PdfParser/Tests/Units/Element/ElementStruct.php
  src/Smalot/PdfParser/Tests/Units/Element/ElementXRef.php
  src/Smalot/PdfParser/Tests/Units/Font.php
  src/Smalot/PdfParser/Tests/Units/Header.php
  src/Smalot/PdfParser/Tests/Units/PDFObject.php
  src/Smalot/PdfParser/Tests/Units/Page.php
  src/Smalot/PdfParser/Tests/Units/Parser.php
  src/Smalot/PdfParser/XObject/Form.php
  src/Smalot/PdfParser/XObject/Image.php
Labels: enhancement

#297 For Pdf data extractor #282 but with the master merged and the TODO solved
  samples/SimpleInvoiceFilledExample1.pdf
  samples/SimpleInvoiceFilledExample2.pdf
  src/Smalot/PdfParser/Element.php
  src/Smalot/PdfParser/Font.php
  src/Smalot/PdfParser/Page.php
  src/Smalot/PdfParser/Tests/Units/Page.php
Labels: enhancement, needs work
