Repository smalot/pdfparser, pull requests merged in 2020-12, with the labels that each got.

#369 ElementName.php: Improve regex performance by removing group naming
  src/Smalot/PdfParser/Element/ElementName.php
Labels: enhancement, needs work

#376 Ditch Travis and use GitHub Actions
  .editorconfig
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .travis.yml
  composer.json
  phpstan.neon
  src/Smalot/PdfParser/Font.php
  src/Smalot/PdfParser/PDFObject.php
  src/Smalot/PdfParser/Page.php
  src/Smalot/PdfParser/RawData/FilterHelper.php
  src/Smalot/PdfParser/RawData/RawDataParser.php
  tests/Integration/Element/ElementArrayTest.php
  tests/Integration/Element/ElementBooleanTest.php
  tests/Integration/Element/ElementDateTest.php
  tests/Integration/Element/ElementMissingTest.php
  tests/Integration/Element/ElementNameTest.php
  tests/Integration/Element/ElementNullTest.php
  tests/Integration/Element/ElementNumericTest.php
  tests/Integration/Element/ElementStringTest.php
  tests/Integration/Element/ElementXRefTest.php
  tests/Integration/ElementTest.php
  tests/Integration/ParserTest.php
  tests/Integration/RawData/FilterHelperTest.php
  tests/TestCase.php
Labels: enhancement, unit tests

#375 First step towards a config object (e.g. adapt font space limit)
  src/Smalot/PdfParser/Config.php
  src/Smalot/PdfParser/Font.php
  src/Smalot/PdfParser/PDFObject.php
  src/Smalot/PdfParser/Parser.php
  tests/Integration/ParserTest.php
  tests/Unit/ConfigTest.php
Labels: enhancement

#378 Implement undefined method in Encoding class
  src/Smalot/PdfParser/Encoding.php
  src/Smalot/PdfParser/Font.php
  tests/Integration/EncodingTest.php
  tests/Integration/FontTest.php
Labels: fix, tests required

#380 Fixes #367 (Call to a member function init() on boolean in Header.php on line 66)
  src/Smalot/PdfParser/Header.php
  tests/Integration/HeaderTest.php
Labels: fix
