Repository smalot/pdfparser, pull requests merged in 2020-10, with the labels that each got.

#345 allow for line breaks when splitting xrefs for id and position
  src/Smalot/PdfParser/Parser.php
  tests/Integration/ParserTest.php
Labels: fix

#349 revived #257: Properly decode ANSI encodings
  samples/InternationalChars.pdf
  samples/bugs/Issue202.pdf
  src/Smalot/PdfParser/Document.php
  src/Smalot/PdfParser/Encoding.php
  src/Smalot/PdfParser/Encoding/PostScriptGlyphs.php
  src/Smalot/PdfParser/Font.php
  src/Smalot/PdfParser/Header.php
  src/Smalot/PdfParser/PDFObject.php
  src/Smalot/PdfParser/Page.php
  src/Smalot/PdfParser/Parser.php
  tests/Integration/ParserTest.php
Labels: fix

#346 process hexadecimal strings containing line breaks, but strip line breaks first (fix #273)
  src/Smalot/PdfParser/Font.php
  tests/Integration/FontTest.php
Labels: fix

#350 getPages() should only ever return elements of type 'Page'
  samples/bugs/Issue331.pdf
  src/Smalot/PdfParser/Pages.php
  tests/Integration/PageTest.php
Labels: enhancement, unit tests

#351 Added a few tests to check current behavior of RawData/FilterHelper.php
  tests/Integration/RawData/FilterHelperTest.php
Labels: unit tests

#362 hotfix for #359 and #360: fallback for glyphs not in the postscript lookup table
  samples/bugs/Issue359.pdf
  src/Smalot/PdfParser/Encoding/PostScriptGlyphs.php
  tests/Integration/ParserTest.php
Labels: fix
