Repository smalot/pdfparser, pull requests merged in 2020-06, with the labels that each got.

#299 Removed TCPDF library and ported used code - Outside tests welcome!
  composer.json
  src/Smalot/PdfParser/Parser.php
  src/Smalot/PdfParser/RawData/FilterHelper.php
  src/Smalot/PdfParser/RawData/RawDataParser.php
  tests/Integration/RawData/FilterHelperTest.php
Labels: enhancement, help wanted

#302 Use SVG icons
  README.md
Labels: enhancement

#306 Allow PHP 8
  .gitattributes
  .scrutinizer.yml
  .travis.yml
  composer.json
  phpstan.neon
Labels: enhancement

#310 Fix array access on integer for php7.4
  .gitignore
  samples/bugs/Issue267_array_access_on_int.pdf
  src/Smalot/PdfParser/Parser.php
  tests/Integration/ParserTest.php
Labels: bugfix

#313 Replacement for #238 (Fix illegal encoding for MacRomanEncoding)
  samples/bugs/Issue229_mac_roman_encoding.pdf
  src/Smalot/PdfParser/Font.php
Labels: bugfix
