Repository smalot/pdfparser, pull requests merged in 2021-04, with the labels that each got.

#405 Bug fix: Consider all PDF white-space characters in object header
  samples/bugs/Issue405.pdf
  src/Smalot/PdfParser/RawData/RawDataParser.php
  tests/Integration/RawData/RawDataParserTest.php
Labels: fix, needs more info

#407 Encoding::__toString complies with PHP specification from now on
  src/Smalot/PdfParser/Encoding.php
  tests/Integration/EncodingTest.php
Labels: fix

#402 Add support for Reversed Chars instruction in BMC blocs
  samples/bugs/Issue398.pdf
  src/Smalot/PdfParser/PDFObject.php
  tests/Integration/PDFObjectTest.php
Labels: enhancement, fix

#406 Replaces #403 (fix Call to a member function getFontSpaceLimit() on null)
  src/Smalot/PdfParser/PDFObject.php
  tests/Integration/FontTest.php
Labels: fix

#383 Introduced PHP 8 support; removed support for PHP 5.6 + 7.0
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .gitignore
  .scrutinizer.yml
  DEVELOPER.md
  Makefile
  README.md
  composer.json
  dev-tools/composer.json
  phpstan.neon
  src/Smalot/PdfParser/Element/ElementXRef.php
  tests/Integration/PageTest.php
  tests/Integration/ParserTest.php
  tests/Integration/RawData/FilterHelperTest.php
  tests/Integration/RawData/RawDataParserTest.php
  tests/TestCase.php
  tests/Unit/ConfigTest.php
Labels: enhancement, help wanted, needs more info

#412 Attempt to fix #410 (failing scrutinizer checks)
  .scrutinizer.yml
  Makefile
Labels: fix, unit tests

#413 Fixes YAML of coding-standards.yml
  .github/workflows/coding-standards.yml
  Makefile
Labels: fix, unit tests

#409 CI workflow: adapted alt autoloader case to match new PHP version usage (7.1+)
  .github/workflows/continuous-integration.yml
Labels: fix, unit tests

#414 Fixes CS issue in Config.php
  src/Smalot/PdfParser/Config.php
Labels: fix, unit tests
