Repository smalot/pdfparser, pull requests merged in 2021-11, with the labels that each got.

#467 Font.php: Optimization of the uchr function
  src/Smalot/PdfParser/Font.php
Labels: enhancement

#481 Fix Scrutinizer-integration: mark PageTest::testGetTextPullRequest457 as "memory-heavy"
  tests/Integration/PageTest.php
Labels: unit tests / CI, fix

#486 Replace usage of str_starts_with in Page.php::isFpdf
  src/Smalot/PdfParser/Page.php
Labels: fix

#479 Fixes #478 (/Index problem)
  samples/bugs/Issue479.pdf
  src/Smalot/PdfParser/RawData/RawDataParser.php
  tests/Integration/PageTest.php
  tests/Integration/RawData/RawDataParserTest.php
Labels: fix

#476 Added decodeMemoryLimit to Config to avoid memory leaks.
  src/Smalot/PdfParser/Config.php
  src/Smalot/PdfParser/RawData/FilterHelper.php
  src/Smalot/PdfParser/RawData/RawDataParser.php
Labels: enhancement, fix
