Repository smalot/pdfparser, pull requests merged in 2022-03, with the labels that each got.

#513 Rework documentation
  DEVELOPER.md
  README.md
  doc/CustomConfig.md
  doc/Developer.md
  doc/Usage.md
Labels: enhancement, documentation

#521 fixes #520 (missing r in composer command in README.md)
  README.md
Labels: fix, documentation

#516 Added font info to dataTm
  doc/Usage.md
  src/Smalot/PdfParser/Config.php
  src/Smalot/PdfParser/Page.php
  tests/Integration/PageTest.php
Labels: enhancement

#517 Added calculateTextWidth function to Font
  doc/Usage.md
  src/Smalot/PdfParser/Font.php
  tests/Integration/FontTest.php
Labels: enhancement
