Repository smalot/pdfparser, pull requests merged in 2022-12, with the labels that each got.

#560 fix: allow to parse null or empty header element
  samples/bugs/Issue557.pdf
  src/Smalot/PdfParser/Parser.php
  tests/Integration/ParserTest.php
Labels: fix

#562 #561 Added optional getText() argument to return limited number of document pages if set
  doc/Usage.md
  src/Smalot/PdfParser/Document.php
  tests/Integration/DocumentTest.php
Labels: enhancement

#566 Extend Github workflow file to run tests in Windows environment
  .github/workflows/continuous-integration.yml
  phpunit-windows.xml
  tests/Integration/FontTest.php
  tests/Integration/PDFObjectTest.php
Labels: enhancement, unit tests / CI

#559 consider scaling by fontSize(Tf, Tfs) and text matrix (Tm)
  src/Smalot/PdfParser/Page.php
  tests/Integration/PageTest.php
Labels: enhancement, fix
