Repository smalot/pdfparser, pull requests merged in 2022-01, with the labels that each got.

#493 added function to parse base64 encoded PDFs
  DEVELOPER.md
  README.md
Labels: enhancement, documentation

#506 Link docs to wiki instead of pdfparser.org
  README.md
Labels: fix, documentation

#509 Add return types to tests methods. Fix todos in phpDocs. Add method's descriptions for Font class.
  src/Smalot/PdfParser/Font.php
  tests/Integration/DocumentTest.php
  tests/Integration/Element/ElementArrayTest.php
  tests/Integration/Element/ElementBooleanTest.php
  tests/Integration/Element/ElementDateTest.php
  tests/Integration/Element/ElementHexaTest.php
  tests/Integration/Element/ElementMissingTest.php
  tests/Integration/Element/ElementNameTest.php
  tests/Integration/Element/ElementNullTest.php
  tests/Integration/Element/ElementNumericTest.php
  tests/Integration/Element/ElementStringTest.php
  tests/Integration/Element/ElementStructTest.php
  tests/Integration/Element/ElementXRefTest.php
  tests/Integration/ElementTest.php
  tests/Integration/EncodingTest.php
  tests/Integration/FontTest.php
  tests/Integration/HeaderTest.php
  tests/Integration/PDFObjectTest.php
  tests/Integration/PageTest.php
  tests/Integration/ParserTest.php
  tests/Integration/RawData/FilterHelperTest.php
  tests/Integration/RawData/RawDataParserTest.php
  tests/TestCase.php
  tests/Unit/ConfigTest.php
Labels: enhancement, unit tests / CI, documentation
