Repository smalot/pdfparser, pull requests merged in 2023-08, with the labels that each got.

#623 Fixes #621: Font::uchr: allow int|float for $code parameter
  samples/bugs/Issue621.pdf
  src/Smalot/PdfParser/Font.php
  tests/PHPUnit/Integration/ParserTest.php
Labels: fix

#622 Allow for CRC23 checksum gzuncompress()
  samples/bugs/Issue592.pdf
  src/Smalot/PdfParser/RawData/FilterHelper.php
  tests/PHPUnit/Integration/RawData/FilterHelperTest.php
Labels: enhancement, fix

#627 Adjust hex/octal string decoding
  src/Smalot/PdfParser/Font.php
  tests/PHPUnit/Integration/FontTest.php
Labels: fix, de-/encoding issue

#624 Account for empty arrays in XMP data
  src/Smalot/PdfParser/Document.php
Labels: enhancement

#630 fix: Fail to identify fonts (name and size) #629
  doc/Usage.md
  samples/bugs/Issue629.pdf
  src/Smalot/PdfParser/Page.php
  tests/PHPUnit/Integration/PageTest.php
Labels: fix

#633 Add a pull request template which contains helpful information
  .github/pull_request_template.md
  src/Smalot/PdfParser/Parser.php
Labels: enhancement, unit tests / CI, documentation

#635 Check for wrong line-endings when getting xref
  src/Smalot/PdfParser/RawData/RawDataParser.php
  tests/PHPUnit/Integration/FontTest.php
Labels: fix, de-/encoding issue
