Repository smalot/pdfparser, pull requests merged in 2023-07, with the labels that each got.

#606 Read XMP Metadata and add it to data returned by getDetails()
  doc/Usage.md
  samples/XMP_Metadata.pdf
  src/Smalot/PdfParser/Document.php
  src/Smalot/PdfParser/Encoding.php
  src/Smalot/PdfParser/Parser.php
  tests/PHPUnit/Integration/DocumentTest.php
  tests/PHPUnit/Integration/EncodingTest.php
Labels: enhancement

#611 Enable PDFDocEncoding support for metadata
  samples/Issue609.pdf
  src/Smalot/PdfParser/Document.php
  src/Smalot/PdfParser/Encoding/PDFDocEncoding.php
  tests/PHPUnit/Integration/DocumentTest.php
Labels: enhancement, encoding issues

#612 Support metadata element names containing spaces
  src/Smalot/PdfParser/Element.php
  tests/PHPUnit/Integration/ElementTest.php
Labels: enhancement

#597 str_replace in Font.php now seems to work as expected
  src/Smalot/PdfParser/Font.php
  tests/PHPUnit/Unit/FontTest.php
Labels: missing or incomplete functionality, fix

#614 Add font fallback + Support for font IDs containing hyphens
  samples/ImproperFontFallback.pdf
  src/Smalot/PdfParser/Encoding/PDFDocEncoding.php
  src/Smalot/PdfParser/PDFObject.php
  tests/PHPUnit/Integration/PDFObjectTest.php
Labels: fix, encoding issues
