Repository smalot/pdfparser, pull requests merged in 2023-09, with the labels that each got.

#640 Better octal and hex-entity decode
  src/Smalot/PdfParser/Font.php
  tests/PHPUnit/Integration/FontTest.php
Labels: fix, de-/encoding issue

#642 Absorb spaces after 'stream' declarations
  src/Smalot/PdfParser/RawData/RawDataParser.php
  tests/PHPUnit/Integration/RawData/RawDataParserTest.php
Labels: fix

#644 Usage.md: change example code to avoid PHP notice
  doc/Usage.md
Labels: fix, documentation
