Repository smalot/pdfparser, pull requests merged in 2023-04, with the labels that each got.

#594 Run cs-fixer after new release of bugfix/cs-fix
  src/Smalot/PdfParser/RawData/RawDataParser.php
Labels: enhancement

#590 Improve performance by not extracting compressed image data if retainImageContent was set to false
  src/Smalot/PdfParser/RawData/RawDataParser.php
Labels: enhancement

#593 Add instructions to get page width and height
  doc/Usage.md
Labels: enhancement, documentation

#580 fix to iconv() illegal character error (issue #549)
  src/Smalot/PdfParser/Font.php
  tests/PHPUnit/Integration/FontTest.php
Labels: fix
